export const INIT_MATRIX = "GAMEBOARD/INIT_MATRIX";
export const RESET_MATRIX = "GAMEBOARD/RESET_MATRIX";

export const RANDOM_TILE = "GAMEBOARD/RANDOM_TILE";

export const MOVE_UP = "GAMEBOARD/MOVE_UP";
export const MOVE_DOWN = "GAMEBOARD/MOVE_DOWN";
export const MOVE_LEFT = "GAMEBOARD/MOVE_LEFT";
export const MOVE_RIGHT = "GAMEBOARD/MOVE_RIGHT";
